
*(The shield uses a little JS to call your backend directly.)*

### Block B-1 — `.github/workflows/ci.yml` for docs repo
```yaml
name: Build Docs
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.12'}
      - run: pip install mkdocs mkdocs-material
      - run: mkdocs gh-deploy --force
